# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self
pool:
  vmImage: ubuntu-latest

steps:
- script: |
    docker login --username sarahhristea --password Sarah1997!

- task: DockerCompose@0
  inputs:
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'docker-compose up -d' 