version: '3'
services:
  server:
   build: server/
   container_name: server
   ports:
      - "80:80"
  proxy:
    build: proxy/
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - server
